services:
  - type: web
    name: checkout-pushinpay-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: PUSHINPAY_API_KEY
        sync: false # Recomenda-se configurar isso manualmente no painel do Render por segurança
